---
title: "figure_4"
author: "Elizabeth McMurchie"
date: '2022-04-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Read in necessary libraries
```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(data.table)
library(janitor)
library(tibble)
```

# Data wrangling
```{r}
wheat <- read_excel("data_files/Supplemental_file_5.xls", sheet = 2)
names(wheat) <- NULL # do not include top header/label row
wheat <- data.frame(lapply(wheat, gsub, pattern = " ", replacement = "_"))
wheat <- data.frame(lapply(wheat, gsub, pattern = "-", replacement = "_"))
wheat <- data.frame(lapply(wheat, gsub, pattern = ",", replacement = ""))
wheat <- wheat %>%
  as.data.frame() %>%
  row_to_names(row_number = 1)
colnames(wheat)[1] <- "Gene"
view(wheat)

barley <- read_excel("data_files/Supplemental_file_5.xls", sheet = 3)
names(barley) <- NULL # do not include top header/label row
barley <- data.frame(lapply(barley, gsub, pattern = " ", replacement = "_"))
barley <- data.frame(lapply(barley, gsub, pattern = ",", replacement = ""))
barley <- barley %>%
  as.data.frame() %>%
  row_to_names(row_number = 1)
colnames(barley)[1] <- "Gene"
colnames(barley)[2] <- "germinating_seed_coleoptile"
colnames(barley)[3] <- "germinating_seed_root"
colnames(barley)[12] <- "3_5_DAP_caryopsis"

barley <- barley %>%
  select(-"10_DAP_caryopsis", -"16_DAP_caryopsis")
view(barley)


#barley <- barley[-1,] # remove header row for ages of plant parts
#view(barley)

grass <- rbind(wheat, barley) %>%
  pivot_longer(!Gene, names_to = "tissue", values_to = "expression") %>%
  mutate(expression = as.numeric(expression)) %>%
  mutate(tissue = as.factor(tissue))
str(grass)

```
# Figure 4a
```{r}
grass4a <- grass %>%
  filter(Gene %in% c("Traes_5BL_E6535628C", "MLOC_44160", "MLOC_35818")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4a)

fig4a <- ggplot(data = grass4a, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#2FBE49", "#FF3333", "#6699FF")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(17, 15, 18)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(4, 10), breaks = c(4:10)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4a

```
# Figure 4b
```{r}
grass4b <- grass %>%
  filter(Gene %in% c("Traes_3B_2A454DB62", "Traes_3B_C8DBBCD0E", "Traes_7AS_EBD5F1F54", "MLOC_68576")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4b)

fig4b <- ggplot(data = grass4b, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#9E5CF8", "#6699FF", "#FF3333", "#2FBE49")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(3, 18, 15, 17)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(4, 14), breaks = c(4:14)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4b
```
# Figure 4c
```{r}
grass4c <- grass %>%
  filter(Gene %in% c("Traes_2BL_E0978B1BC", "Traes_7DL_CAF83263E", "Traes_2DL_71F120931", "MLOC_53973")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4c)

fig4c <- ggplot(data = grass4c, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#9E5CF8", "#6699FF", "#2FBE49", "#FF3333")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(3, 18, 17, 15)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(3, 10), breaks = c(3:10)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4c
```
# Figure 4d
```{r}
grass4d <- grass %>%
  filter(Gene %in% c("Traes_5AL_13E2DEC48", "Traes_5DS_B05596869", "Traes_5DL_9CC4EC839", "Traes_2DL_903A29CBA", "MLOC_61901")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4d)

fig4d <- ggplot(data = grass4d, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#20CADB", "#9E5CF8", "#6699FF", "#2FBE49", "#FF3333")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(8, 3, 18, 17, 15)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(2, 11), breaks = c(2:11)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4d
```

# Figure 4e
```{r}
grass4e <- grass %>%
  filter(Gene %in% c("Traes_5DL_8CE2482E6", "Traes_5AL_852A1474C", "MLOC_57021")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4e)

fig4e <- ggplot(data = grass4e, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#2FBE49", "#FF3333", "#6699FF")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(17, 15, 18)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(6, 11), breaks = c(6:11)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4e
```
# Figure 4f
```{r}
grass4f <- grass %>%
  filter(Gene %in% c("Traes_6BL_ED40C8806", "Traes_6AL_A0A31AA9F", "Traes_6DL_C215BACFD", "MLOC_52387")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grass4f)

fig4f <- ggplot(data = grass4f, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#9E5CF8", "#FF3333", "#6699FF", "#2FBE49")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(4, 15, 18, 17)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(3, 11), breaks = c(3:11)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
fig4f
```

# Figure S3a
```{r}
grassS3a <- grass %>%
  filter(Gene %in% c("Traes_3DS_E0EF3E9AB", "MLOC_74854", "MLOC_71606")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grassS3a)

figS3a <- ggplot(data = grassS3a, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#2FBE49", "#FF3333", "#6699FF")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(17, 15, 18)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(5, 14), breaks = c(5:14)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray"), axis.text.x = element_text(angle = 90))
figS3a
```

# Figure S3b
```{r}
grassS3b <- grass %>%
  filter(Gene %in% c("Traes_4DS_2D08DBB36", "Traes_5AL_1AF8FD33F", "Traes_2BL_879586172", "Traes_5BS_400779D59", "Traes_4AL_68B60F6AA", "MLOC_64619", "MLOC_57326", "MLOC_58552")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grassS3b)

figS3b <- ggplot(data = grassS3b, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#B096D3", "#FF27F8", "#FF9E00", "#2FBE49", "#20CADB", "#6699FF", "#FF3333",  "#9E5CF8")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(3, 5, 16, 17, 8, 18, 15, 4)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(3, 14), breaks = c(3:14)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
figS3b
```
# Figure S3c
```{r}
grassS3c <- grass %>%
  filter(Gene %in% c("Traes_5DL_8C647BFE2", "Traes_7BS_7BA1E9F73", "Traes_7DS_4AF5C695F", "Traes_3AS_B4247C855", "Traes_5AL_EBF32FE10", "Traes_7DS_C8938031B", "MLOC_56472")) %>%
  mutate(tissue = fct_relevel(tissue, c("germinating_seed_coleoptile", "germinating_seed_root",
                                  "germinating_seed_embryo", "seedling_root", "seedling_crown",
                                  "seedling_leaf", "immature_inflorescence", "floral_bracts_before_anthesis",
                                  "pistil_before_anthesis", "anthers_before_anthesis", "3_5_DAP_caryopsis",
                                  "22_DAP_embryo", "22_DAP_endosperm")))

view(grassS3c)

figS3c <- ggplot(data = grassS3c, aes(x = tissue, y = expression, group = Gene)) +
  geom_line(aes(color = Gene)) +
  scale_color_manual(values = c("#B096D3", "#9E5CF8", "#20CADB", "#6699FF", "#FF3333", "#2FBE49", "#FF9E00")) +
  geom_point(aes(color = Gene, shape = Gene), size = 3) +
  scale_shape_manual(values = c(3, 4, 8, 18, 15, 17, 16)) +
  ylab("Log2 expression value") +
  scale_x_discrete("", labels = c("Germinating seed, coleoptile", "Germinating seed, root", "Germinating seed, embryo", "Seedling, root", "Seedling, crown", "Seedling, leaf", "Immature inflorescence", "Floral bracts, before anthesis", "Pistil, before anthesis", "Anthers, before anthesis", "3-5 DAP caryopsis", "22 DAP embryo", "22 DAP endosperm")) +
  scale_y_continuous(limits = c(2, 14), breaks = c(2:14)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(color = "gray", linetype = 2), axis.text.x = element_text(angle = 90))
figS3c
```

