---
title: "Heat_Map_Analysis_Icecream_Bean's_Version"
author: "Tyler L Foster"
date: "4/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load these packages
library(readxl)
library(tidyverse)
library(gplots)
```

```{r}
#create directories for plots later
dir.create('./heat_map_plots')
```

```{r}
#Unzipping the supplemental materials folder found on our GitHub repository
unzip("Peng_Supp_Materials.zip")
```

# Arabidopsis Heat Map

```{r}
#read in the 97-2003 file, change the sheet accordingly, skip the nasty 1st row, sheet 1 is arabidopsis 
arabidopsis_expression_v <- read_excel("Supplemental file 5.xls", sheet = 1, skip = 1)
```

```{r}
#change 1st column name to 'Gene'
colnames(arabidopsis_expression_v)[1] <- "Gene"
```

```{r}
#creates a datamatrix, which heatmap.2 can utilize later, to generate the desired plot
arabidopsis_matrix <- data.matrix(arabidopsis_expression_v)
```

```{r}
#change the row names in the matrix to the gene names from our dataframe
row.names(arabidopsis_matrix) <- arabidopsis_expression_v$Gene
```

```{r}
#selecting all rows and columns 2-64 of our datamatrix as column 1 is a gene number
arabidopsis_matrix <- arabidopsis_matrix[,2:64]
```

```{r}
#Creates a color palette for our heatmap
colfunc <- colorRampPalette(c("blue2", "white", "red2"))
```

```{r}
bmp(file="./heat_map_plots/icecream_bean's_arabidopsis_heatmap.bmp",
   width=16, height = 10, units = "in", res=500)
heatmap.2(arabidopsis_matrix,
          dendrogram = "col", #only draw a column dendogram
          breaks = 100, #determines the number of color transitions
          trace = "none", #turns off the trace lines inside the heat map
          margins = c(5,0), #sets margins around plot
          labRow = FALSE, #turns off row labels
          col = colfunc(99), #use the color palette we created above
          cexCol = 0.7, #changes column label font
          lmat = rbind(c(0,3,0),c(2,1,0),c(0,4,0)), #manually placing key objects of figure
          lwid = c(0.05, 0.1, 0.05), #changes dimensions of the array cell widths
          lhei = c(0.43, 3.5, 0.6), #alter dimensions of array cell heights
          key.title = NA, #turns off key title
          density.info="none", #turns off the trace lines in the key
          key.par=list(mar=c(2, 0, 4,0) ), #tweaks specific key parameters
          key.xtickfun = function() {breaks = pretty(parent.frame()$breaks)          
            breaks = breaks[c(1,length(breaks))]             
            list(at = parent.frame()$scale01(breaks), labels = breaks) #changes the tick marks on key
            })
```

# Wheat Heat Map

```{r}
#read in the 97-2003 file, change the sheet accordingly, skip the nasty 1st row, sheet 2 is wheat 
wheat_expression_v <- read_excel("Supplemental file 5.xls", sheet = 2, skip = 1)
```

```{r}
#change 1st column name to 'Gene'
colnames(wheat_expression_v)[1] <- "Gene"
```

```{r}
#creates a datamatrix, which heatmap.2 can utilize later, to generate the desired plot
wheat_matrix <- data.matrix(wheat_expression_v)
```

```{r}
#change the row names in the matrix to the gene names from our dataframe
row.names(wheat_matrix) <- wheat_expression_v$Gene
```

```{r}
#selecting all rows and columns 2-14 of our datamatrix as column 1 is a gene number
wheat_matrix <- wheat_matrix[,2:14]
```

```{r}
bmp(file="./heat_map_plots/icecream_bean's_wheat_heatmap.bmp",
    width=6, height = 4, units = "in", res=500)
heatmap.2(wheat_matrix,
          dendrogram = "col", #only draw a column dendogram
          breaks = 100, #determines the number of color transitions
          trace = "none", #turns off the trace lines inside the heat map
          margins = c(10,0), #widens margins around plot
          labRow = FALSE, #turns off row labels
          col = colfunc(99), #use the color palette we created above
          cexCol = 1, #changes column label font
          lmat = rbind(c(0,3,0),c(2,1,0),c(0,4,0)), #manually placing key objects of figure
          lwid = c(0.05, 0.05, 0.05), #changes dimensions of the array cell widths
          lhei = c(0.43, 2.6, 0.6), #alter dimensions of array cell heights
          key.title = NA, #turns off key title
          density.info="none", #turns off the trace lines in the key
          key.par=list(mar=c(2, 0, 1.8,0) ), #tweaks specific key parameters
          key.xtickfun = function() {breaks = pretty(parent.frame()$breaks)          
            breaks = breaks[c(1,length(breaks))]             
            list(at = parent.frame()$scale01(breaks), labels = breaks) #changes the tick marks on key
            })
```

# Barley Heat Map

```{r}
#read in the 97-2003 file, change the sheet accordingly, skip the nasty 1st row, sheet 3 is barley 
barley_expression_v <- read_excel("Supplemental file 5.xls", sheet = 3, skip = 1)
```

```{r}
#change 1st column name to 'Gene'
colnames(barley_expression_v)[1] <- "Gene"
```

```{r}
#creates a datamatrix, which heatmap.2 can utilize later, to generate the desired plot
barley_matrix <- data.matrix(barley_expression_v)
```

```{r}
#change the row names in the matrix to the gene names from our dataframe
row.names(barley_matrix) <- barley_expression_v$Gene
```

```{r}
#selecting all rows and columns 2-16 of our datamatrix as column 1 is just a gene number
barley_matrix <- barley_matrix[,2:16]
```

```{r}
bmp(file="./heat_map_plots/icecream_bean's_barley_heatmap.bmp",
    width=6, height = 4, units = "in", res=500)
heatmap.2(barley_matrix,
          dendrogram = "col", #only draw a column dendogram
          breaks = 100, #determines the number of color transitions
          trace = "none", #turns off the trace lines inside the heat map
          margins = c(10,0), #widens margins around plot
          labRow = FALSE, #turns off row labels
          col = colfunc(99), #use the color palette we created above
          cexCol = 1, #changes column label font
          key.title = NA, #turns off key title
          density.info="none", #turns off the trace lines in the key          
          lmat = rbind(c(0,3,0),c(2,1,0),c(0,4,0)), #manually placing key objects of figure
          lwid = c(0.05, 0.05, 0.05), #changes dimensions of the array cell widths
          lhei = c(0.43, 2.6, 0.6), #alter dimensions of array cell heights
          key.par=list(mar=c(2, 0, 1.8,0) ), #tweaks specific key parameters
          key.xtickfun = function() {breaks = pretty(parent.frame()$breaks)          
            breaks = breaks[c(1,length(breaks))]             
            list(at = parent.frame()$scale01(breaks), labels = breaks) #changes the tick marks on key
            })
```